import { Toaster } from "@/components/ui/toaster";
import clsx from "clsx";
import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import NextTopLoader from "nextjs-toploader";
import { PAGE_TITLE } from "@/lib/constants/PageTitle";
import { fetchCurrentTimeEntry } from "@/lib/data";
import Time from "@/lib/utils/Time";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  variable: "--font-serif",
});

export async function generateMetadata() {
  let duration = "";
  try {
    const { data } = await fetchCurrentTimeEntry();
    const { formattedTime } = Time.getTimeFromSeconds(
      Time.getSecondsFromPrevTime(new Date(data.startTime), true),
    );
    duration = `${formattedTime} |`;
  } catch (error) {
    console.error(error);
  }

  return {
    title: duration + PAGE_TITLE,
    description: "Generated by create next app",
  };
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={clsx(
          inter.variable,
          poppins.variable,
          "flex min-h-screen flex-col bg-slate-200 font-serif",
        )}
      >
        <NextTopLoader color="#4799eb" />

        <StoreProvider>
          {children}
          <Toaster />
        </StoreProvider>
      </body>
    </html>
  );
}
